v = """ESDSSSSSSEEEUENDNNNNUNWDWWUEEEEEDEE
EEWWWWSSSEEWWSSSEEEEUEENNNNNNDSSSSUSEDUSEDUNEDUNED
NNNNUEEDEEEEWWWWSSSSSSEEEEUEEDNNNNNNSSSEEEENNNSSSSSSUEEDNNNNUN
EDUNEDUSEDUSEDSWWWEEESSSUEEDNNNNNNEEESSSNNNEEESSSSSSUEEDNNNNNNEEESSSWWUSSSEEEEEEE
DWWNNNNNNEEUEEDSSSSSSEEEEUEEDNNNNNNUEEDSSSSSSEEEEUEEEENDNNNNSSWWEEEEUEENNNDEEEEWWWWSSSSSS
EEEEUEENNNNNNDSSSSSSEEEENNNNNNUEEDEEEEEEWWWSSSSSSUEEEEEDNNNNNNEEEEWWWWSSSEEWWSSSEEEEUEEEEN
DNNNNSSWWEEEEUEENNNDSSSSSSEEEENNNWWWEENNNWWUEEEEEDSSSSSSEEEENNNNNNWWWWUEEEEEEDEEEEEEWWWSSSSSSUEEEEEDEENNNNNNWW"""
N = 1000
NN = 10
g = [[' ' for __ in range(N)] for _ in range(N)]
x, y = NN, NN
g[x][y] = '#'
tt = v.replace("\n", "").split('D')
print(tt, len(tt))

i = 1
db = dict(N=(0, -1), S=(0, 1), E=(1, 0), W=(-1, 0))
mx = x
for t in tt[1:]:
    # print(t)
    for c in t:
        if c in 'NSEW':
            xx, yy = db[c]
            x, y = x + xx, y + yy
            g[y][x] = '#'
            mx = max(mx, x)
        else:
            break
    i += 1
    x, y = mx + 10, NN

for i in range(N):
    print("".join(g[i]))
